//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evebury.Gs1.Message.R3.Schema.CatalogueItem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evebury.Gs1.Message.R3.Schema.CatalogueItem.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlcoholInformationModule {
            get {
                object obj = ResourceManager.GetObject("AlcoholInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AllergenInformationModule {
            get {
                object obj = ResourceManager.GetObject("AllergenInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AnimalFeedingModule {
            get {
                object obj = ResourceManager.GetObject("AnimalFeedingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApparelInformationModule {
            get {
                object obj = ResourceManager.GetObject("ApparelInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AudienceOrPlayerInformationModule {
            get {
                object obj = ResourceManager.GetObject("AudienceOrPlayerInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AudioVisualMediaContentInformationModule {
            get {
                object obj = ResourceManager.GetObject("AudioVisualMediaContentInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AudioVisualMediaProductDescriptionInformationModule {
            get {
                object obj = ResourceManager.GetObject("AudioVisualMediaProductDescriptionInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AudioVisualMediaProductionInformationModule {
            get {
                object obj = ResourceManager.GetObject("AudioVisualMediaProductionInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AwardPrizeModule {
            get {
                object obj = ResourceManager.GetObject("AwardPrizeModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BasicTypes {
            get {
                object obj = ResourceManager.GetObject("BasicTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BatteryInformationModule {
            get {
                object obj = ResourceManager.GetObject("BatteryInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BusinessScope {
            get {
                object obj = ResourceManager.GetObject("BusinessScope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemConfirmation {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemConfirmation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemHierarchicalWithdrawal {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemHierarchicalWithdrawal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemNotification {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemPublication {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemPublication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemRegistrationResponse {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemRegistrationResponse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatalogueItemSubscription {
            get {
                object obj = ResourceManager.GetObject("CatalogueItemSubscription", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CertificationInformationModule {
            get {
                object obj = ResourceManager.GetObject("CertificationInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChemicalRegulationInformationModule {
            get {
                object obj = ResourceManager.GetObject("ChemicalRegulationInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChildNutritionInformationModule {
            get {
                object obj = ResourceManager.GetObject("ChildNutritionInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ConsumerInstructionsModule {
            get {
                object obj = ResourceManager.GetObject("ConsumerInstructionsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ControlledSubstanceModule {
            get {
                object obj = ResourceManager.GetObject("ControlledSubstanceModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CopyrightInformationModule {
            get {
                object obj = ResourceManager.GetObject("CopyrightInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DairyFishMeatPoultryItemModule {
            get {
                object obj = ResourceManager.GetObject("DairyFishMeatPoultryItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DangerousSubstanceInformationModule {
            get {
                object obj = ResourceManager.GetObject("DangerousSubstanceInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeliveryPurchasingInformationModule {
            get {
                object obj = ResourceManager.GetObject("DeliveryPurchasingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DietInformationModule {
            get {
                object obj = ResourceManager.GetObject("DietInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DocumentIdentification {
            get {
                object obj = ResourceManager.GetObject("DocumentIdentification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DurableGoodsCharacteristicsModule {
            get {
                object obj = ResourceManager.GetObject("DurableGoodsCharacteristicsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DutyFeeTaxInformationModule {
            get {
                object obj = ResourceManager.GetObject("DutyFeeTaxInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ElectronicDeviceCharacteristicsInformationModule {
            get {
                object obj = ResourceManager.GetObject("ElectronicDeviceCharacteristicsInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FarmingAndProcessingInformationModule {
            get {
                object obj = ResourceManager.GetObject("FarmingAndProcessingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FoodAndBeverageIngredientModule {
            get {
                object obj = ResourceManager.GetObject("FoodAndBeverageIngredientModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FoodAndBeveragePreparationServingModule {
            get {
                object obj = ResourceManager.GetObject("FoodAndBeveragePreparationServingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FoodAndBeveragePropertiesInformationModule {
            get {
                object obj = ResourceManager.GetObject("FoodAndBeveragePropertiesInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GdsnCommon {
            get {
                object obj = ResourceManager.GetObject("GdsnCommon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GS1Response {
            get {
                object obj = ResourceManager.GetObject("GS1Response", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HealthcareItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("HealthcareItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HealthRelatedInformationModule {
            get {
                object obj = ResourceManager.GetObject("HealthRelatedInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HealthWellnessPackagingMarkingModule {
            get {
                object obj = ResourceManager.GetObject("HealthWellnessPackagingMarkingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LanguageCode {
            get {
                object obj = ResourceManager.GetObject("LanguageCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightingDeviceModule {
            get {
                object obj = ResourceManager.GetObject("LightingDeviceModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Manifest {
            get {
                object obj = ResourceManager.GetObject("Manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MarketingInformationModule {
            get {
                object obj = ResourceManager.GetObject("MarketingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MaterialModule {
            get {
                object obj = ResourceManager.GetObject("MaterialModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MedicalDeviceTradeItemModule {
            get {
                object obj = ResourceManager.GetObject("MedicalDeviceTradeItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MovieRevenueInformationModule {
            get {
                object obj = ResourceManager.GetObject("MovieRevenueInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NonfoodIngredientModule {
            get {
                object obj = ResourceManager.GetObject("NonfoodIngredientModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NonGTINLogisticsUnitInformationModule {
            get {
                object obj = ResourceManager.GetObject("NonGTINLogisticsUnitInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NutritionalInformationModule {
            get {
                object obj = ResourceManager.GetObject("NutritionalInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ONIXPublicationFileInformationModule {
            get {
                object obj = ResourceManager.GetObject("ONIXPublicationFileInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpticsDeviceInformationModule {
            get {
                object obj = ResourceManager.GetObject("OpticsDeviceInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OrganismClassificationModule {
            get {
                object obj = ResourceManager.GetObject("OrganismClassificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PackagingInformationModule {
            get {
                object obj = ResourceManager.GetObject("PackagingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PackagingMarkingModule {
            get {
                object obj = ResourceManager.GetObject("PackagingMarkingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PackagingSustainabilityModule {
            get {
                object obj = ResourceManager.GetObject("PackagingSustainabilityModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Partner {
            get {
                object obj = ResourceManager.GetObject("Partner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PharmaceuticalItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("PharmaceuticalItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PhysicalResourceUsageInformationModule {
            get {
                object obj = ResourceManager.GetObject("PhysicalResourceUsageInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlaceOfItemActivityModule {
            get {
                object obj = ResourceManager.GetObject("PlaceOfItemActivityModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlumbingHVACPipeInformationModule {
            get {
                object obj = ResourceManager.GetObject("PlumbingHVACPipeInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProductCharacteristicsModule {
            get {
                object obj = ResourceManager.GetObject("ProductCharacteristicsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProductFormulationStatementModule {
            get {
                object obj = ResourceManager.GetObject("ProductFormulationStatementModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProductInformationModule {
            get {
                object obj = ResourceManager.GetObject("ProductInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PromotionalItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("PromotionalItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PropellantInformationModule {
            get {
                object obj = ResourceManager.GetObject("PropellantInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PublicationTitleRatingModule {
            get {
                object obj = ResourceManager.GetObject("PublicationTitleRatingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReferencedFileDetailInformationModule {
            get {
                object obj = ResourceManager.GetObject("ReferencedFileDetailInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RegistryCatalogueItem {
            get {
                object obj = ResourceManager.GetObject("RegistryCatalogueItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RegulatedTradeItemModule {
            get {
                object obj = ResourceManager.GetObject("RegulatedTradeItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RequestForCatalogueItemNotification {
            get {
                object obj = ResourceManager.GetObject("RequestForCatalogueItemNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SafetyDataSheetModule {
            get {
                object obj = ResourceManager.GetObject("SafetyDataSheetModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SalesInformationModule {
            get {
                object obj = ResourceManager.GetObject("SalesInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SecurityTagInformationModule {
            get {
                object obj = ResourceManager.GetObject("SecurityTagInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharedCommon {
            get {
                object obj = ResourceManager.GetObject("SharedCommon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SoftwareSystemRequirementsModule {
            get {
                object obj = ResourceManager.GetObject("SoftwareSystemRequirementsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StandardBusinessDocumentHeader {
            get {
                object obj = ResourceManager.GetObject("StandardBusinessDocumentHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SustainabilityModule {
            get {
                object obj = ResourceManager.GetObject("SustainabilityModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItem {
            get {
                object obj = ResourceManager.GetObject("TradeItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemDataCarrierAndIdentificationModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemDataCarrierAndIdentificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemDescriptionModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemDescriptionModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemDisposalInformationModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemDisposalInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemHandlingModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemHandlingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemHierarchyModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemHierarchyModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemHumidityInformationModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemHumidityInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemLicensingModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemLicensingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemLifespanModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemLifespanModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemMeasurementsModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemMeasurementsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemSizeModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemSizeModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TradeItemTemperatureInformationModule {
            get {
                object obj = ResourceManager.GetObject("TradeItemTemperatureInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TransportationHazardousClassificationModule {
            get {
                object obj = ResourceManager.GetObject("TransportationHazardousClassificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VariableTradeItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("VariableTradeItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VideoDisplayDeviceInformationModule {
            get {
                object obj = ResourceManager.GetObject("VideoDisplayDeviceInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WarrantyInformationModule {
            get {
                object obj = ResourceManager.GetObject("WarrantyInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
