//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evebury.Gs1.Message.R3.Xsl.CatalogueItem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatalogueItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogueItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evebury.Gs1.Message.R3.Xsl.CatalogueItem.CatalogueItem", typeof(CatalogueItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] alcoholInformationModule {
            get {
                object obj = ResourceManager.GetObject("alcoholInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] allergenInformationModule {
            get {
                object obj = ResourceManager.GetObject("allergenInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] animalFeedingModule {
            get {
                object obj = ResourceManager.GetObject("animalFeedingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] audienceOrPlayerInformationModule {
            get {
                object obj = ResourceManager.GetObject("audienceOrPlayerInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] audioVisualMediaContentInformationModule {
            get {
                object obj = ResourceManager.GetObject("audioVisualMediaContentInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] audioVisualMediaProductDescriptionInformationModule {
            get {
                object obj = ResourceManager.GetObject("audioVisualMediaProductDescriptionInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] batteryInformationModule {
            get {
                object obj = ResourceManager.GetObject("batteryInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] catalogueItemNotification {
            get {
                object obj = ResourceManager.GetObject("catalogueItemNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] certificationInformationModule {
            get {
                object obj = ResourceManager.GetObject("certificationInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] childNutritionInformationModule {
            get {
                object obj = ResourceManager.GetObject("childNutritionInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] component_rules {
            get {
                object obj = ResourceManager.GetObject("component_rules", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] consumerInstructionsModule {
            get {
                object obj = ResourceManager.GetObject("consumerInstructionsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] copyrightInformationModule {
            get {
                object obj = ResourceManager.GetObject("copyrightInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dairyFishMeatPoultryItemModule {
            get {
                object obj = ResourceManager.GetObject("dairyFishMeatPoultryItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dangerousSubstanceInformationModule {
            get {
                object obj = ResourceManager.GetObject("dangerousSubstanceInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] deliveryPurchasingInformationModule {
            get {
                object obj = ResourceManager.GetObject("deliveryPurchasingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dietInformationModule {
            get {
                object obj = ResourceManager.GetObject("dietInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dutyFeeTaxInformationModule {
            get {
                object obj = ResourceManager.GetObject("dutyFeeTaxInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] farmingAndProcessingInformationModule {
            get {
                object obj = ResourceManager.GetObject("farmingAndProcessingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] foodAndBeverageIngredientModule {
            get {
                object obj = ResourceManager.GetObject("foodAndBeverageIngredientModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] foodAndBeveragePreparationServingModule {
            get {
                object obj = ResourceManager.GetObject("foodAndBeveragePreparationServingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] foodAndBeveragePropertiesInformationModule {
            get {
                object obj = ResourceManager.GetObject("foodAndBeveragePropertiesInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] healthRelatedInformationModule {
            get {
                object obj = ResourceManager.GetObject("healthRelatedInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hierarchy_rules {
            get {
                object obj = ResourceManager.GetObject("hierarchy_rules", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] item_rules {
            get {
                object obj = ResourceManager.GetObject("item_rules", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lightingDeviceModule {
            get {
                object obj = ResourceManager.GetObject("lightingDeviceModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] marketingInformationModule {
            get {
                object obj = ResourceManager.GetObject("marketingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] materialModule {
            get {
                object obj = ResourceManager.GetObject("materialModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] measurementUnit {
            get {
                object obj = ResourceManager.GetObject("measurementUnit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] medicalDeviceTradeItemModule {
            get {
                object obj = ResourceManager.GetObject("medicalDeviceTradeItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nonfoodIngredientModule {
            get {
                object obj = ResourceManager.GetObject("nonfoodIngredientModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nonGTINLogisticsUnitInformationModule {
            get {
                object obj = ResourceManager.GetObject("nonGTINLogisticsUnitInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nutritionalInformationModule {
            get {
                object obj = ResourceManager.GetObject("nutritionalInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oNIXPublicationFileInformationModule {
            get {
                object obj = ResourceManager.GetObject("oNIXPublicationFileInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] organismClassificationModule {
            get {
                object obj = ResourceManager.GetObject("organismClassificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packagingInformationModule {
            get {
                object obj = ResourceManager.GetObject("packagingInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packagingMarkingModule {
            get {
                object obj = ResourceManager.GetObject("packagingMarkingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] physicalResourceUsageInformationModule {
            get {
                object obj = ResourceManager.GetObject("physicalResourceUsageInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] placeOfItemActivityModule {
            get {
                object obj = ResourceManager.GetObject("placeOfItemActivityModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] plumbingHVACPipeInformationModule {
            get {
                object obj = ResourceManager.GetObject("plumbingHVACPipeInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] productFormulationStatementModule {
            get {
                object obj = ResourceManager.GetObject("productFormulationStatementModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] productInformationModule {
            get {
                object obj = ResourceManager.GetObject("productInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] promotionalItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("promotionalItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] referencedFileDetailInformationModule {
            get {
                object obj = ResourceManager.GetObject("referencedFileDetailInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regulatedTradeItemModule {
            get {
                object obj = ResourceManager.GetObject("regulatedTradeItemModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] safetyDataSheetModule {
            get {
                object obj = ResourceManager.GetObject("safetyDataSheetModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] salesInformationModule {
            get {
                object obj = ResourceManager.GetObject("salesInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemDataCarrierAndIdentificationModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemDataCarrierAndIdentificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemDescriptionModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemDescriptionModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemHandlingModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemHandlingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemHierarchyModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemHierarchyModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemHumidityInformationModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemHumidityInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemLicensingModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemLicensingModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemLifespanModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemLifespanModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemMeasurementsModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemMeasurementsModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemSizeModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemSizeModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tradeItemTemperatureInformationModule {
            get {
                object obj = ResourceManager.GetObject("tradeItemTemperatureInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] transportationHazardousClassificationModule {
            get {
                object obj = ResourceManager.GetObject("transportationHazardousClassificationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] variableTradeItemInformationModule {
            get {
                object obj = ResourceManager.GetObject("variableTradeItemInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] warrantyInformationModule {
            get {
                object obj = ResourceManager.GetObject("warrantyInformationModule", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
