//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evebury.Gs1.Message.R3.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Market {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Market() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evebury.Gs1.Message.R3.Resource.Market", typeof(Market).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Market.
        /// </summary>
        internal static string _001 {
            get {
                return ResourceManager.GetString("001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string _004 {
            get {
                return ResourceManager.GetString("004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string _008 {
            get {
                return ResourceManager.GetString("008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        internal static string _010 {
            get {
                return ResourceManager.GetString("010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string _012 {
            get {
                return ResourceManager.GetString("012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa.
        /// </summary>
        internal static string _016 {
            get {
                return ResourceManager.GetString("016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        internal static string _020 {
            get {
                return ResourceManager.GetString("020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        internal static string _024 {
            get {
                return ResourceManager.GetString("024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        internal static string _028 {
            get {
                return ResourceManager.GetString("028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string _031 {
            get {
                return ResourceManager.GetString("031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string _032 {
            get {
                return ResourceManager.GetString("032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string _036 {
            get {
                return ResourceManager.GetString("036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string _040 {
            get {
                return ResourceManager.GetString("040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        internal static string _044 {
            get {
                return ResourceManager.GetString("044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string _048 {
            get {
                return ResourceManager.GetString("048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        internal static string _050 {
            get {
                return ResourceManager.GetString("050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string _051 {
            get {
                return ResourceManager.GetString("051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        internal static string _052 {
            get {
                return ResourceManager.GetString("052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string _056 {
            get {
                return ResourceManager.GetString("056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda.
        /// </summary>
        internal static string _060 {
            get {
                return ResourceManager.GetString("060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        internal static string _064 {
            get {
                return ResourceManager.GetString("064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia (Plurinational State of).
        /// </summary>
        internal static string _068 {
            get {
                return ResourceManager.GetString("068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        internal static string _070 {
            get {
                return ResourceManager.GetString("070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        internal static string _072 {
            get {
                return ResourceManager.GetString("072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouvet Island.
        /// </summary>
        internal static string _074 {
            get {
                return ResourceManager.GetString("074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string _076 {
            get {
                return ResourceManager.GetString("076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        internal static string _084 {
            get {
                return ResourceManager.GetString("084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Indian Ocean Territory.
        /// </summary>
        internal static string _086 {
            get {
                return ResourceManager.GetString("086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands.
        /// </summary>
        internal static string _090 {
            get {
                return ResourceManager.GetString("090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands (British).
        /// </summary>
        internal static string _092 {
            get {
                return ResourceManager.GetString("092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        internal static string _096 {
            get {
                return ResourceManager.GetString("096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Union.
        /// </summary>
        internal static string _097 {
            get {
                return ResourceManager.GetString("097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroon.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string _124 {
            get {
                return ResourceManager.GetString("124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabo Verde.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayman Islands.
        /// </summary>
        internal static string _136 {
            get {
                return ResourceManager.GetString("136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central African Republic.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        internal static string _144 {
            get {
                return ResourceManager.GetString("144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chad.
        /// </summary>
        internal static string _148 {
            get {
                return ResourceManager.GetString("148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string _152 {
            get {
                return ResourceManager.GetString("152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string _156 {
            get {
                return ResourceManager.GetString("156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan, Province of China.
        /// </summary>
        internal static string _158 {
            get {
                return ResourceManager.GetString("158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Island.
        /// </summary>
        internal static string _162 {
            get {
                return ResourceManager.GetString("162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocos (Keeling) Islands.
        /// </summary>
        internal static string _166 {
            get {
                return ResourceManager.GetString("166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string _170 {
            get {
                return ResourceManager.GetString("170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoros.
        /// </summary>
        internal static string _174 {
            get {
                return ResourceManager.GetString("174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayotte.
        /// </summary>
        internal static string _175 {
            get {
                return ResourceManager.GetString("175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        internal static string _178 {
            get {
                return ResourceManager.GetString("178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo, Democratic Republic of the.
        /// </summary>
        internal static string _180 {
            get {
                return ResourceManager.GetString("180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Islands.
        /// </summary>
        internal static string _184 {
            get {
                return ResourceManager.GetString("184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string _188 {
            get {
                return ResourceManager.GetString("188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string _191 {
            get {
                return ResourceManager.GetString("191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        internal static string _192 {
            get {
                return ResourceManager.GetString("192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        internal static string _196 {
            get {
                return ResourceManager.GetString("196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czechia.
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string _208 {
            get {
                return ResourceManager.GetString("208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominica.
        /// </summary>
        internal static string _212 {
            get {
                return ResourceManager.GetString("212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string _214 {
            get {
                return ResourceManager.GetString("214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string _218 {
            get {
                return ResourceManager.GetString("218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string _222 {
            get {
                return ResourceManager.GetString("222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial Guinea.
        /// </summary>
        internal static string _226 {
            get {
                return ResourceManager.GetString("226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        internal static string _231 {
            get {
                return ResourceManager.GetString("231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea.
        /// </summary>
        internal static string _232 {
            get {
                return ResourceManager.GetString("232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string _233 {
            get {
                return ResourceManager.GetString("233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        internal static string _234 {
            get {
                return ResourceManager.GetString("234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkland Islands (Malvinas).
        /// </summary>
        internal static string _238 {
            get {
                return ResourceManager.GetString("238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Georgia and the South Sandwich Islands.
        /// </summary>
        internal static string _239 {
            get {
                return ResourceManager.GetString("239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        internal static string _242 {
            get {
                return ResourceManager.GetString("242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string _246 {
            get {
                return ResourceManager.GetString("246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åland Islands.
        /// </summary>
        internal static string _248 {
            get {
                return ResourceManager.GetString("248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string _250 {
            get {
                return ResourceManager.GetString("250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Guiana.
        /// </summary>
        internal static string _254 {
            get {
                return ResourceManager.GetString("254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia.
        /// </summary>
        internal static string _258 {
            get {
                return ResourceManager.GetString("258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Southern Territories.
        /// </summary>
        internal static string _260 {
            get {
                return ResourceManager.GetString("260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        internal static string _262 {
            get {
                return ResourceManager.GetString("262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        internal static string _266 {
            get {
                return ResourceManager.GetString("266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string _268 {
            get {
                return ResourceManager.GetString("268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia.
        /// </summary>
        internal static string _270 {
            get {
                return ResourceManager.GetString("270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine, State of.
        /// </summary>
        internal static string _275 {
            get {
                return ResourceManager.GetString("275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string _276 {
            get {
                return ResourceManager.GetString("276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        internal static string _288 {
            get {
                return ResourceManager.GetString("288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        internal static string _292 {
            get {
                return ResourceManager.GetString("292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        internal static string _296 {
            get {
                return ResourceManager.GetString("296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string _300 {
            get {
                return ResourceManager.GetString("300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenada.
        /// </summary>
        internal static string _308 {
            get {
                return ResourceManager.GetString("308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadeloupe.
        /// </summary>
        internal static string _312 {
            get {
                return ResourceManager.GetString("312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        internal static string _316 {
            get {
                return ResourceManager.GetString("316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string _320 {
            get {
                return ResourceManager.GetString("320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea.
        /// </summary>
        internal static string _324 {
            get {
                return ResourceManager.GetString("324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        internal static string _328 {
            get {
                return ResourceManager.GetString("328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        internal static string _332 {
            get {
                return ResourceManager.GetString("332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heard Island and McDonald Islands.
        /// </summary>
        internal static string _334 {
            get {
                return ResourceManager.GetString("334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy See.
        /// </summary>
        internal static string _336 {
            get {
                return ResourceManager.GetString("336", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string _340 {
            get {
                return ResourceManager.GetString("340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string _344 {
            get {
                return ResourceManager.GetString("344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        internal static string _348 {
            get {
                return ResourceManager.GetString("348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string _352 {
            get {
                return ResourceManager.GetString("352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string _356 {
            get {
                return ResourceManager.GetString("356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string _360 {
            get {
                return ResourceManager.GetString("360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran (Islamic Republic of).
        /// </summary>
        internal static string _364 {
            get {
                return ResourceManager.GetString("364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        internal static string _368 {
            get {
                return ResourceManager.GetString("368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string _372 {
            get {
                return ResourceManager.GetString("372", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        internal static string _376 {
            get {
                return ResourceManager.GetString("376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string _380 {
            get {
                return ResourceManager.GetString("380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côte d&apos;Ivoire.
        /// </summary>
        internal static string _384 {
            get {
                return ResourceManager.GetString("384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        internal static string _388 {
            get {
                return ResourceManager.GetString("388", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string _392 {
            get {
                return ResourceManager.GetString("392", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string _398 {
            get {
                return ResourceManager.GetString("398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea (Democratic People&apos;s Republic of).
        /// </summary>
        internal static string _408 {
            get {
                return ResourceManager.GetString("408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea, Republic of.
        /// </summary>
        internal static string _410 {
            get {
                return ResourceManager.GetString("410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao People&apos;s Democratic Republic.
        /// </summary>
        internal static string _418 {
            get {
                return ResourceManager.GetString("418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string _422 {
            get {
                return ResourceManager.GetString("422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        internal static string _426 {
            get {
                return ResourceManager.GetString("426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string _428 {
            get {
                return ResourceManager.GetString("428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        internal static string _430 {
            get {
                return ResourceManager.GetString("430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string _434 {
            get {
                return ResourceManager.GetString("434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string _438 {
            get {
                return ResourceManager.GetString("438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string _440 {
            get {
                return ResourceManager.GetString("440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string _442 {
            get {
                return ResourceManager.GetString("442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao.
        /// </summary>
        internal static string _446 {
            get {
                return ResourceManager.GetString("446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        internal static string _450 {
            get {
                return ResourceManager.GetString("450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        internal static string _454 {
            get {
                return ResourceManager.GetString("454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        internal static string _458 {
            get {
                return ResourceManager.GetString("458", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        internal static string _462 {
            get {
                return ResourceManager.GetString("462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        internal static string _466 {
            get {
                return ResourceManager.GetString("466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string _470 {
            get {
                return ResourceManager.GetString("470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martinique.
        /// </summary>
        internal static string _474 {
            get {
                return ResourceManager.GetString("474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        internal static string _478 {
            get {
                return ResourceManager.GetString("478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        internal static string _480 {
            get {
                return ResourceManager.GetString("480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string _484 {
            get {
                return ResourceManager.GetString("484", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string _492 {
            get {
                return ResourceManager.GetString("492", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string _496 {
            get {
                return ResourceManager.GetString("496", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova, Republic of.
        /// </summary>
        internal static string _498 {
            get {
                return ResourceManager.GetString("498", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string _499 {
            get {
                return ResourceManager.GetString("499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montserrat.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        internal static string _508 {
            get {
                return ResourceManager.GetString("508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        internal static string _512 {
            get {
                return ResourceManager.GetString("512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        internal static string _516 {
            get {
                return ResourceManager.GetString("516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        internal static string _520 {
            get {
                return ResourceManager.GetString("520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        internal static string _524 {
            get {
                return ResourceManager.GetString("524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string _528 {
            get {
                return ResourceManager.GetString("528", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curaçao.
        /// </summary>
        internal static string _531 {
            get {
                return ResourceManager.GetString("531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        internal static string _533 {
            get {
                return ResourceManager.GetString("533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sint Maarten (Dutch part).
        /// </summary>
        internal static string _534 {
            get {
                return ResourceManager.GetString("534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaire, Sint Eustatius and Saba.
        /// </summary>
        internal static string _535 {
            get {
                return ResourceManager.GetString("535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Caledonia.
        /// </summary>
        internal static string _540 {
            get {
                return ResourceManager.GetString("540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        internal static string _548 {
            get {
                return ResourceManager.GetString("548", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string _554 {
            get {
                return ResourceManager.GetString("554", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string _558 {
            get {
                return ResourceManager.GetString("558", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        internal static string _562 {
            get {
                return ResourceManager.GetString("562", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        internal static string _566 {
            get {
                return ResourceManager.GetString("566", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niue.
        /// </summary>
        internal static string _570 {
            get {
                return ResourceManager.GetString("570", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norfolk Island.
        /// </summary>
        internal static string _574 {
            get {
                return ResourceManager.GetString("574", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string _578 {
            get {
                return ResourceManager.GetString("578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Mariana Islands.
        /// </summary>
        internal static string _580 {
            get {
                return ResourceManager.GetString("580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Minor Outlying Islands.
        /// </summary>
        internal static string _581 {
            get {
                return ResourceManager.GetString("581", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia (Federated States of).
        /// </summary>
        internal static string _583 {
            get {
                return ResourceManager.GetString("583", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshall Islands.
        /// </summary>
        internal static string _584 {
            get {
                return ResourceManager.GetString("584", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        internal static string _585 {
            get {
                return ResourceManager.GetString("585", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        internal static string _586 {
            get {
                return ResourceManager.GetString("586", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string _591 {
            get {
                return ResourceManager.GetString("591", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinea.
        /// </summary>
        internal static string _598 {
            get {
                return ResourceManager.GetString("598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string _600 {
            get {
                return ResourceManager.GetString("600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string _604 {
            get {
                return ResourceManager.GetString("604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        internal static string _608 {
            get {
                return ResourceManager.GetString("608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitcairn.
        /// </summary>
        internal static string _612 {
            get {
                return ResourceManager.GetString("612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string _616 {
            get {
                return ResourceManager.GetString("616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string _620 {
            get {
                return ResourceManager.GetString("620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        internal static string _624 {
            get {
                return ResourceManager.GetString("624", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor-Leste.
        /// </summary>
        internal static string _626 {
            get {
                return ResourceManager.GetString("626", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string _630 {
            get {
                return ResourceManager.GetString("630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        internal static string _634 {
            get {
                return ResourceManager.GetString("634", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réunion.
        /// </summary>
        internal static string _638 {
            get {
                return ResourceManager.GetString("638", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string _642 {
            get {
                return ResourceManager.GetString("642", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Federation.
        /// </summary>
        internal static string _643 {
            get {
                return ResourceManager.GetString("643", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        internal static string _646 {
            get {
                return ResourceManager.GetString("646", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Barthélemy.
        /// </summary>
        internal static string _652 {
            get {
                return ResourceManager.GetString("652", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Helena, Ascension and Tristan da Cunha.
        /// </summary>
        internal static string _654 {
            get {
                return ResourceManager.GetString("654", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Kitts and Nevis.
        /// </summary>
        internal static string _659 {
            get {
                return ResourceManager.GetString("659", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anguilla.
        /// </summary>
        internal static string _660 {
            get {
                return ResourceManager.GetString("660", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        internal static string _662 {
            get {
                return ResourceManager.GetString("662", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Martin (French part).
        /// </summary>
        internal static string _663 {
            get {
                return ResourceManager.GetString("663", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Pierre and Miquelon.
        /// </summary>
        internal static string _666 {
            get {
                return ResourceManager.GetString("666", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Vincent and the Grenadines.
        /// </summary>
        internal static string _670 {
            get {
                return ResourceManager.GetString("670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        internal static string _674 {
            get {
                return ResourceManager.GetString("674", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome and Principe.
        /// </summary>
        internal static string _678 {
            get {
                return ResourceManager.GetString("678", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        internal static string _682 {
            get {
                return ResourceManager.GetString("682", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        internal static string _686 {
            get {
                return ResourceManager.GetString("686", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string _688 {
            get {
                return ResourceManager.GetString("688", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        internal static string _690 {
            get {
                return ResourceManager.GetString("690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        internal static string _694 {
            get {
                return ResourceManager.GetString("694", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string _702 {
            get {
                return ResourceManager.GetString("702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string _703 {
            get {
                return ResourceManager.GetString("703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viet Nam.
        /// </summary>
        internal static string _704 {
            get {
                return ResourceManager.GetString("704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string _705 {
            get {
                return ResourceManager.GetString("705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalia.
        /// </summary>
        internal static string _706 {
            get {
                return ResourceManager.GetString("706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string _710 {
            get {
                return ResourceManager.GetString("710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        internal static string _716 {
            get {
                return ResourceManager.GetString("716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string _724 {
            get {
                return ResourceManager.GetString("724", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Sudan.
        /// </summary>
        internal static string _728 {
            get {
                return ResourceManager.GetString("728", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        internal static string _729 {
            get {
                return ResourceManager.GetString("729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Sahara.
        /// </summary>
        internal static string _732 {
            get {
                return ResourceManager.GetString("732", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        internal static string _740 {
            get {
                return ResourceManager.GetString("740", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svalbard and Jan Mayen.
        /// </summary>
        internal static string _744 {
            get {
                return ResourceManager.GetString("744", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eswatini.
        /// </summary>
        internal static string _748 {
            get {
                return ResourceManager.GetString("748", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string _752 {
            get {
                return ResourceManager.GetString("752", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string _756 {
            get {
                return ResourceManager.GetString("756", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian Arab Republic.
        /// </summary>
        internal static string _760 {
            get {
                return ResourceManager.GetString("760", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string _762 {
            get {
                return ResourceManager.GetString("762", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        internal static string _764 {
            get {
                return ResourceManager.GetString("764", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        internal static string _768 {
            get {
                return ResourceManager.GetString("768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokelau.
        /// </summary>
        internal static string _772 {
            get {
                return ResourceManager.GetString("772", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        internal static string _776 {
            get {
                return ResourceManager.GetString("776", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad and Tobago.
        /// </summary>
        internal static string _780 {
            get {
                return ResourceManager.GetString("780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        internal static string _784 {
            get {
                return ResourceManager.GetString("784", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string _788 {
            get {
                return ResourceManager.GetString("788", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string _792 {
            get {
                return ResourceManager.GetString("792", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string _795 {
            get {
                return ResourceManager.GetString("795", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turks and Caicos Islands.
        /// </summary>
        internal static string _796 {
            get {
                return ResourceManager.GetString("796", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvalu.
        /// </summary>
        internal static string _798 {
            get {
                return ResourceManager.GetString("798", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda.
        /// </summary>
        internal static string _800 {
            get {
                return ResourceManager.GetString("800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string _804 {
            get {
                return ResourceManager.GetString("804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Macedonia.
        /// </summary>
        internal static string _807 {
            get {
                return ResourceManager.GetString("807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string _818 {
            get {
                return ResourceManager.GetString("818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom of Great Britain and Northern Ireland.
        /// </summary>
        internal static string _826 {
            get {
                return ResourceManager.GetString("826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernsey.
        /// </summary>
        internal static string _831 {
            get {
                return ResourceManager.GetString("831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jersey.
        /// </summary>
        internal static string _832 {
            get {
                return ResourceManager.GetString("832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Man.
        /// </summary>
        internal static string _833 {
            get {
                return ResourceManager.GetString("833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania, United Republic of.
        /// </summary>
        internal static string _834 {
            get {
                return ResourceManager.GetString("834", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        internal static string _840 {
            get {
                return ResourceManager.GetString("840", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands (U.S.).
        /// </summary>
        internal static string _850 {
            get {
                return ResourceManager.GetString("850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        internal static string _854 {
            get {
                return ResourceManager.GetString("854", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        internal static string _858 {
            get {
                return ResourceManager.GetString("858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string _860 {
            get {
                return ResourceManager.GetString("860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela (Bolivarian Republic of).
        /// </summary>
        internal static string _862 {
            get {
                return ResourceManager.GetString("862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallis and Futuna.
        /// </summary>
        internal static string _876 {
            get {
                return ResourceManager.GetString("876", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        internal static string _882 {
            get {
                return ResourceManager.GetString("882", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen.
        /// </summary>
        internal static string _887 {
            get {
                return ResourceManager.GetString("887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        internal static string _894 {
            get {
                return ResourceManager.GetString("894", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Assistance.
        /// </summary>
        internal static string D_A {
            get {
                return ResourceManager.GetString("D_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non EU.
        /// </summary>
        internal static string NON_EU {
            get {
                return ResourceManager.GetString("NON_EU", resourceCulture);
            }
        }
    }
}
